spring:
  application:
    name: hello-client

server:
  port: 8888

hello-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082
    ServerListRefreshInterval: 15000
